### ISSUE TITLE
Date and time should be zero padded

### ISSUE THREAD

**Issue by gaudat** [aaasssdddwww/back-home-safe#2]
In the government app the month, day and hour fields are zero padded to 2 digits.
![image](https://user-images.githubusercontent.com/7353556/107600892-0a46bb80-6c60-11eb-9dbe-462fb56de97d.png)
Here is your app's behavior for reference.
![image](https://user-images.githubusercontent.com/7353556/107601158-cf915300-6c60-11eb-85e9-b47a3981438d.png)

**Comment by leavehksafe** [comment]
Hi, just fixed this in pull request #4.

**Comment by aaasssdddwww** [comment]
fixed, thx
